# Generated by Django 3.1.1 on 2020-10-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteapp.post', verbose_name='Post commented'),
        ),
    ]
